module Smithy
  module Client
    module Identities
      class HttpApiKey < Identity
        def initialize: (key: String, **untyped options) -> void
        attr_reader key: String
      end
    end
  end
end
