module Smithy
  module Client
    module Identities
      class HttpLogin < Identity
        def initialize: (username: String, password: String, **untyped options) -> void
        attr_reader username: String
        attr_reader password: String
      end
    end
  end
end
