module Seahorse
  # A module mixed into Structs that provides utility methods.
  module Structure
    # Deeply converts the Struct into a hash. Structure members that
    # are `nil` are omitted from the resultant hash.
    #
    # @return [Hash]
    def to_h: (?untyped obj) -> untyped

    alias to_hash to_h

    private

    def _to_h_struct: (untyped obj) -> untyped

    def _to_h_hash: (untyped obj) -> untyped
  end
end
