module Hearth
  module Query
    class Param
      def initialize: (String name, ?(String | Array[String])? value) -> void

      attr_reader name: String

      attr_reader value: (String | Array[String])

      def to_s: () -> String

      def ==: (Param other) -> bool

      def <=>: (Param other) -> bool
    end
  end
end
