require: rubocop-rake

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0

Gemspec/RequireMFA:
  Enabled: false

Layout/LineLength:
  Max: 80

Metrics:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*.rb'


Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'


Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'
