module Hearth
  module EventStream
    class AsyncOutput[DATA] < Output[DATA]
      def initialize: (response: Response, encoder: Encoder, ?error: ApiError?, ?data: Structure?, ?metadata: Hash[Symbol, untyped]) -> void

      def end_input_stream: () -> void

      def join: () -> bool

      def kill: () -> void
    end
  end
end
