module Hearth
  module EventStream
    class Decoder
      def initialize: (message_decoder: _MessageDecoder, event_handler: HandlerBase) -> void

      def headers=: (Hash[String, String]) -> void

      def write: (String) -> void
    end
  end
end