module Hearth
  module EventStream
    class HandlerBase
      def initialize: () -> void

      def on_raw_event: () { (Message) -> void } -> void

      def on_error: () { (StandardError) -> void } -> void

      def on_error_event: () { (String, ?String) -> void } -> void

      def on_exception_event: () { (Object) -> void} -> void

      def on_headers: () { (Hash[String, String]) -> void} -> void

      def emit_headers: (Hash[String, String]) -> void

      def emit: (Message) -> void
    end
  end
end