module Hearth
  module EventStream
    # Represents a HeaderValue in an EventStream::Message.
    class HeaderValue
      def initialize: (value: untyped, type: String) -> void

      attr_reader value: untyped

      attr_reader type: String
    end
  end
end
