module Hearth
  module EventStream
    interface _MessageEncoder
      def encode: (Message) -> String
      def encode_headers: (Hash[String, HeaderValue]) -> String
    end

    interface _MessageDecoder
      def decode: (String) -> [Message | nil, bool]
    end

  end
end
