module Weather
  class Client < Smithy::Client::Base
    def self.new: (
      ?convert_params: bool,
      ?endpoint: String,
      ?endpoint_provider: Weather::EndpointProvider,
      ?http_ca_file: String,
      ?http_ca_path: String,
      ?http_cert: OpenSSL::X509::Certificate,
      ?http_cert_store: OpenSSL::X509::Store,
      ?http_continue_timeout: Numeric,
      ?http_debug_output: bool,
      ?http_keep_alive_timeout: Numeric,
      ?http_key: OpenSSL::PKey::RSA | OpenSSL::PKey::DSA,
      ?http_open_timeout: Numeric,
      ?http_proxy: URI::HTTP | String,
      ?http_read_timeout: Numeric,
      ?http_ssl_timeout: Numeric,
      ?http_verify_mode: Integer,
      ?http_write_timeout: Numeric,
      ?log_level: Symbol,
      ?logger: Logger,
      ?raise_response_errors: bool,
      ?validate_params: bool,
    ) -> void
    | (?Hash[Symbol, untyped]) -> void

    interface _GetCityResponse
      include Smithy::Client::_Output[Types::GetCityOutput]
      def name: () -> String?
      def coordinates: () -> Types::CityCoordinates?
    end
      def get_city: (
        ?city_id: String
      ) -> _GetCityResponse
      | (?Hash[Symbol, untyped], ?Hash[Symbol, untyped]) -> _GetCityResponse

    interface _GetCurrentTimeResponse
      include Smithy::Client::_Output[Types::GetCurrentTimeOutput]
      def time: () -> Time?
    end
    def get_current_time: (?Hash[Symbol, untyped], ?Hash[Symbol, untyped]) -> _GetCurrentTimeResponse

    interface _GetForecastResponse
      include Smithy::Client::_Output[Types::GetForecastOutput]
      def chance_of_rain: () -> Float?
    end
      def get_forecast: (
        ?city_id: String
      ) -> _GetForecastResponse
      | (?Hash[Symbol, untyped], ?Hash[Symbol, untyped]) -> _GetForecastResponse

    interface _ListCitiesResponse
      include Smithy::Client::_Output[Types::ListCitiesOutput]
      def next_token: () -> String?
      def items: () -> Array[Types::CitySummary]?
    end
      def list_cities: (
        ?next_token: String,
        ?page_size: Integer
      ) -> _ListCitiesResponse
      | (?Hash[Symbol, untyped], ?Hash[Symbol, untyped]) -> _ListCitiesResponse
  end
end
