module Weather
  class EndpointParameters
    include Smithy::Model::Structure

    def initialize: (
      ?endpoint: String,
    ) -> void
    | (?Hash[Symbol, untyped]) -> void
  end

  attr_accessor endpoint: String?
end
