module Weather
  module Schema
    CityCoordinates: Smithy::Schema::Shapes::StructureShape
    CityId: Smithy::Schema::Shapes::StringShape
    CitySummaries: Smithy::Schema::Shapes::ListShape
    CitySummary: Smithy::Schema::Shapes::StructureShape
    GetCityInput: Smithy::Schema::Shapes::StructureShape
    GetCityOutput: Smithy::Schema::Shapes::StructureShape
    GetCurrentTimeOutput: Smithy::Schema::Shapes::StructureShape
    GetForecastInput: Smithy::Schema::Shapes::StructureShape
    GetForecastOutput: Smithy::Schema::Shapes::StructureShape
    ListCitiesInput: Smithy::Schema::Shapes::StructureShape
    ListCitiesOutput: Smithy::Schema::Shapes::StructureShape
    NoSuchResource: Smithy::Schema::Shapes::StructureShape
  end
end
