module Weather
  module Types

    class CityCoordinates
      include Smithy::Model::Structure

      def initialize: (
        ?latitude: Float,
        ?longitude: Float,
      ) -> void
      | (?Hash[Symbol, untyped]) -> void

      attr_accessor latitude: Float?
      attr_accessor longitude: Float?
    end

    class CitySummary
      include Smithy::Model::Structure

      def initialize: (
        ?city_id: String,
        ?name: String,
      ) -> void
      | (?Hash[Symbol, untyped]) -> void

      attr_accessor city_id: String?
      attr_accessor name: String?
    end

    class GetCityInput
      include Smithy::Model::Structure

      def initialize: (
        ?city_id: String,
      ) -> void
      | (?Hash[Symbol, untyped]) -> void

      attr_accessor city_id: String?
    end

    class GetCityOutput
      include Smithy::Model::Structure

      def initialize: (
        ?name: String,
        ?coordinates: Types::CityCoordinates,
      ) -> void
      | (?Hash[Symbol, untyped]) -> void

      attr_accessor name: String?
      attr_accessor coordinates: Types::CityCoordinates?
    end

    class GetCurrentTimeOutput
      include Smithy::Model::Structure

      def initialize: (
        ?time: Time,
      ) -> void
      | (?Hash[Symbol, untyped]) -> void

      attr_accessor time: Time?
    end

    class GetForecastInput
      include Smithy::Model::Structure

      def initialize: (
        ?city_id: String,
      ) -> void
      | (?Hash[Symbol, untyped]) -> void

      attr_accessor city_id: String?
    end

    class GetForecastOutput
      include Smithy::Model::Structure

      def initialize: (
        ?chance_of_rain: Float,
      ) -> void
      | (?Hash[Symbol, untyped]) -> void

      attr_accessor chance_of_rain: Float?
    end

    class ListCitiesInput
      include Smithy::Model::Structure

      def initialize: (
        ?next_token: String,
        ?page_size: Integer,
      ) -> void
      | (?Hash[Symbol, untyped]) -> void

      attr_accessor next_token: String?
      attr_accessor page_size: Integer?
    end

    class ListCitiesOutput
      include Smithy::Model::Structure

      def initialize: (
        ?next_token: String,
        ?items: Array[Types::CitySummary],
      ) -> void
      | (?Hash[Symbol, untyped]) -> void

      attr_accessor next_token: String?
      attr_accessor items: Array[Types::CitySummary]?
    end

    class NoSuchResource
      include Smithy::Model::Structure

      def initialize: (
        ?resource_type: String,
      ) -> void
      | (?Hash[Symbol, untyped]) -> void

      attr_accessor resource_type: String?
    end
  end
end
