module Smithy
  module Schema
    module Shapes
      class Shape
        def initialize: (?Hash[Symbol, untyped]) ?{ (self) -> void } -> void

        attr_accessor id: String?
        attr_accessor traits: Hash[String, untyped]
        def []: (Symbol) -> Object
        def []=: (Symbol, Object) -> void
      end

      class ShapeRef
        def initialize: (?Hash[Symbol, untyped]) -> void

        attr_reader shape: Shape
        attr_reader member_name: String?
        attr_reader traits: Hash[String, untyped]
        def []: (Symbol) -> Object
        def []=: (Symbol, Object) -> void
      end

      class Structure < Shape
        attr_accessor members: Hash[Symbol, ShapeRef]
        def add_member: (Symbol, ShapeRef) -> ShapeRef
        def member?: (Symbol?) -> bool
        def member: (Symbol) -> ShapeRef?
      end

      class ServiceShape < Shape
        include Enumerable[Shapes::OperationShape]
        attr_accessor name: String
        attr_accessor version: String?
        attr_accessor operations: Hash[Symbol, Shapes::OperationShape]
        def add_operation: (Symbol, Shapes::OperationShape) -> void
        def operation: (Symbol) -> Shapes::OperationShape
        def operation_names: () -> Array[Symbol]
      end

      class OperationShape < Shape
        attr_accessor name: String
        attr_accessor input: ShapeRef
        attr_accessor output: ShapeRef
        attr_accessor errors: Array[ShapeRef]
      end

      class BigDecimalShape < Shape
      end

      class BlobShape < Shape
      end

      class BooleanShape < Shape
      end

      class DocumentShape < Shape
      end

      class EnumShape < Structure
      end

      class IntegerShape < Shape
      end

      class IntEnumShape < Structure
      end

      class FloatShape < Shape
      end

      class ListShape < Shape
        attr_accessor member: ShapeRef
      end

      class MapShape < Shape
        attr_accessor key: ShapeRef
        attr_accessor value: ShapeRef
      end

      class StringShape < Shape
      end

      class StructureShape < Structure
        attr_accessor type: Class
      end

      class TimestampShape < Shape
      end

      class UnionShape < Structure
        attr_accessor type: Class
        attr_accessor member_types: Hash[Symbol, Class]
        attr_accessor members_by_type: Hash[Class, ShapeRef]

        def add_member: (Symbol, Class, ShapeRef) -> ShapeRef
        def member_type?: (Symbol) -> bool
        def member_type: (Symbol) -> Class?
        def member_by_type?: (Class) -> bool
        def member_by_type: (Class) -> ShapeRef?
      end

      module Prelude
        BigDecimal: BigDecimalShape
        BigInteger: IntegerShape
        Blob: BlobShape
        Boolean: BooleanShape
        Byte: IntegerShape
        Document: DocumentShape
        Double: FloatShape
        Float: FloatShape
        Integer: IntegerShape
        Long: IntegerShape
        PrimitiveBoolean: BooleanShape
        PrimitiveByte: IntegerShape
        PrimitiveDouble: FloatShape
        PrimitiveFloat: FloatShape
        PrimitiveInteger: IntegerShape
        PrimitiveShort: IntegerShape
        PrimitiveLong: IntegerShape
        Short: IntegerShape
        String: StringShape
        Timestamp: TimestampShape
        Unit: StructureShape
      end
    end
  end
end