module Smithy
  module Schema
    module Shapes
      class Shape
        def initialize: (?Hash[Symbol, untyped]) ?{ (self) -> void } -> void

        attr_reader target: Shape
        attr_accessor id: String
        attr_accessor name: String
        attr_accessor traits: Hash[String, untyped]
        def []: (Symbol) -> Object
        def []=: (Symbol, Object) -> void
      end

      class MemberShape
        def initialize: (?Hash[Symbol, untyped]) -> void

        attr_accessor target: Shape
        attr_accessor name: String?
        attr_accessor traits: Hash[String, untyped]
        def []: (Symbol) -> Object
        def []=: (Symbol, Object) -> void
      end

      class ServiceShape < Shape
        include Enumerable[Shapes::OperationShape]
        attr_accessor version: String?
        attr_accessor operations: Hash[Symbol, Shapes::OperationShape]
        def add_operation: (Symbol, Shapes::OperationShape) -> void
        def operation: (Symbol) -> Shapes::OperationShape
        def operation_names: () -> Array[Symbol]
      end

      class OperationShape < Shape
        attr_accessor name: String
        attr_accessor input: Shape
        attr_accessor output: Shape
        attr_accessor errors: Array[Shape]
      end

      class BigDecimalShape < Shape
      end

      class BlobShape < Shape
      end

      class BooleanShape < Shape
      end

      class DocumentShape < Shape
      end

      class EnumShape < Shape
        attr_accessor members: Hash[Symbol, MemberShape]
        def add_member: (Symbol, MemberShape) -> MemberShape
        def member?: (Symbol?) -> bool
        def member: (Symbol) -> MemberShape?
      end

      class IntegerShape < Shape
      end

      class IntEnumShape < Shape
        attr_accessor members: Hash[Symbol, MemberShape]
        def add_member: (Symbol, MemberShape) -> MemberShape
        def member?: (Symbol?) -> bool
        def member: (Symbol) -> MemberShape?
      end

      class FloatShape < Shape
      end

      class ListShape < Shape
        attr_accessor member: MemberShape
      end

      class MapShape < Shape
        attr_accessor key: MemberShape
        attr_accessor value: MemberShape
      end

      class StringShape < Shape
      end

      class StructureShape < Shape
        attr_accessor members: Hash[Symbol, MemberShape]
        attr_accessor type: Class | Struct[untyped]
        def add_member: (Symbol, MemberShape) -> MemberShape
        def member?: (Symbol?) -> bool
        def member: (Symbol) -> MemberShape?
      end

      class TimestampShape < Shape
      end

      class UnionShape < Shape
        attr_accessor members: Hash[Symbol, MemberShape]
        attr_accessor member_types: Hash[Symbol, Class]
        attr_accessor members_by_type: Hash[Class, [Symbol, MemberShape]]
        attr_accessor type: Class | Struct[untyped]
        def add_member: (Symbol, Class, MemberShape) -> MemberShape
        def member?: (Symbol?) -> bool
        def member: (Symbol) -> MemberShape?
        def member_type?: (Symbol) -> bool
        def member_type: (Symbol) -> Class?
        def member_by_type?: (Class) -> bool
        def member_by_type: (Class) -> [Symbol, MemberShape]?
      end

      module Prelude
        BigDecimal: BigDecimalShape
        BigInteger: IntegerShape
        Blob: BlobShape
        Boolean: BooleanShape
        Byte: IntegerShape
        Document: DocumentShape
        Double: FloatShape
        Float: FloatShape
        Integer: IntegerShape
        Long: IntegerShape
        PrimitiveBoolean: BooleanShape
        PrimitiveByte: IntegerShape
        PrimitiveDouble: FloatShape
        PrimitiveFloat: FloatShape
        PrimitiveInteger: IntegerShape
        PrimitiveShort: IntegerShape
        PrimitiveLong: IntegerShape
        Short: IntegerShape
        String: StringShape
        Timestamp: TimestampShape
        Unit: StructureShape
      end
    end
  end
end
