module Hearth
  module Telemetry
    class TelemetryProvider
      def initialize: (?tracer_provider: _TracerProvider, ?context_manager: _ContextManager) -> void

      attr_reader tracer_provider: _TracerProvider

      attr_reader context_manager: _ContextManager
    end
  end
end
