module Hearth
  module Retry
    # Standard retry strategy for retrying requests.
    class Standard < Strategy
      # @param [#call] backoff (ExponentialBackoff) A callable object that
      #   calculates a backoff delay for a retry attempt.
      # @param [Integer] max_attempts (3) The maximum number of attempts that
      #   will be made for a single request, including the initial attempt.
      def initialize: (?backoff: untyped, ?max_attempts: ::Integer) -> void

      def acquire_initial_retry_token: (?untyped? _token_scope) -> untyped

      def refresh_retry_token: (untyped retry_token, untyped error_info) -> (nil | untyped)

      def record_success: (untyped retry_token) -> untyped
    end
  end
end
