module Hearth
  module Retry
    class Strategy
      def acquire_initial_retry_token: (?String? _token_scope) -> Token

      def refresh_retry_token: (Token _retry_token, _ErrorInspector _error_info) -> (nil | Token)

      def record_success: (Token _retry_token) -> Token
    end
  end
end
