module Hearth
  module Retry
    # Interface for retry strategies.
    class Strategy
      def acquire_initial_retry_token: (?untyped? _token_scope) -> untyped

      def refresh_retry_token: (untyped _retry_token, untyped _error_info) -> untyped

      def record_success: (untyped _retry_token) -> untyped
    end
  end
end
