module Smithy
  module Client
    interface _ReadableIO
      def read: (?nil, ?string outbuf) -> String
        | (int? length, ?string outbuf) -> String?
    end

    interface _IdentityProvider
      def identity: (Hash[untyped, untyped] properties) -> Identity
    end

    type endpoint_url = String | URI::HTTP | URI::HTTPS
  end
end