module Smithy
  module Client
    interface _WritableIO
      def write: (*_ToS) -> Integer
    end

    interface _ReadableIO
      def read: (?nil, ?string outbuf) -> String
        | (int? length, ?string outbuf) -> String?
    end

    type endpoint_url = String | URI::HTTP | URI::HTTPS

    interface _Protocol
      def build: (HandlerContext context) -> void
      def parse: (HandlerContext context) -> void
      def error: (HandlerContext context, HTTP::Response response) -> void
    end
  end
end