# frozen_string_literal: true

module Hearth
  module Waiters
    class WaiterFailed < StandardError
    end

    class FailureStateError < WaiterFailed
    end

    class MaxWaitTimeExceededError < WaiterFailed
    end

    class UnexpectedError < WaiterFailed
    end
  end
end
