module ShapeService
  class AuthParameters
    def initialize: (
      operation_name: Symbol,
    ) -> void
    | (?Hash[Symbol, untyped]) -> void

    attr_accessor operation_name: Symbol
  end
end
