module ShapeService
  module Schema
    include Smithy::Schema::Shapes

    BigDecimal: BigDecimalShape
    BigInteger: IntegerShape
    Blob: BlobShape
    Boolean: BooleanShape
    Byte: IntegerShape
    Document: DocumentShape
    Double: FloatShape
    Enum: EnumShape
    Float: FloatShape
    IntEnum: IntEnumShape
    Integer: IntegerShape
    List: ListShape
    Long: IntegerShape
    Map: MapShape
    OperationInputOutput: StructureShape
    Short: IntegerShape
    String: StringShape
    Structure: StructureShape
    Timestamp: TimestampShape
    Union: UnionShape

    ShapeService: ServiceShape
  end
end
