module Hearth
  module HTTP
    # Represents an HTTP Response.
    # @api private
    class Response
      # @param [Integer] status
      # @param [Headers] headers
      # @param [IO] body
      def initialize: (?status: ::Integer status, ?headers: Headers headers, ?body: IO body) -> Response

      # @return [Integer]
      attr_accessor status: Integer

      # @return [Headers]
      attr_accessor headers: Headers

      # @return [IO]
      attr_accessor body: IO
    end
  end
end
