module Weather
  module Schema
    include Smithy::Schema::Shapes

    CityCoordinates: StructureShape
    CityId: StringShape
    CitySummaries: ListShape
    CitySummary: StructureShape
    GetCityInput: StructureShape
    GetCityOutput: StructureShape
    GetCurrentTimeOutput: StructureShape
    GetForecastInput: StructureShape
    GetForecastOutput: StructureShape
    ListCitiesInput: StructureShape
    ListCitiesOutput: StructureShape
    NoSuchResource: StructureShape

    Weather: ServiceShape
  end
end
