module Hearth
  module Identities
    # Identity class for login authentication.
    class HTTPLogin < Identities::Base
      def initialize: (username: untyped, password: untyped, **untyped kwargs) -> void

      # @return [String]
      attr_reader username: untyped

      # @return [String]
      attr_reader password: untyped
    end
  end
end
