module Hearth
  module Retry
    # Adaptive retry strategy for retrying requests.
    class Adaptive < Strategy
      # @param [#call] backoff (ExponentialBackoff) A callable object that
      #   calculates a backoff delay for a retry attempt.
      # @param [Integer] max_attempts (3) The maximum number of attempts that
      #   will be made for a single request, including the initial attempt.
      # @param [Boolean] wait_to_fill When true, the request will sleep until
      #   there is sufficient client side capacity to retry the request. When
      #   false, the request will raise a `CapacityNotAvailableError` and will
      #   not retry instead of sleeping.
      def initialize: (?backoff: untyped, ?max_attempts: ::Integer, ?wait_to_fill: bool) -> void

      def acquire_initial_retry_token: (?untyped? _token_scope) -> untyped

      def refresh_retry_token: (untyped retry_token, untyped error_info) -> (nil | untyped)

      def record_success: (untyped retry_token) -> untyped
    end
  end
end
