module Hearth
  module Interceptor
    # Context provided to interceptor hook methods.
    class Context
      # @param [Struct] input
      # @param [Hearth::Request] request
      # @param [Hearth::Response] response
      # @param [Hearth::Output] output
      # @param [Hash] attributes ({}) additional interceptor data
      def initialize: (input: untyped, request: untyped, response: untyped, output: untyped, ?attributes: ::Hash[untyped, untyped]) -> void

      # @return [Struct] Modeled input, i.e. Types::<Operation>Input
      attr_reader input: untyped

      # @return [Hearth::Request]
      attr_reader request: untyped

      # @return [Hearth::Response]
      attr_reader response: untyped

      # @return [Hearth::Output] only available to hooks after transmit
      attr_reader output: untyped

      # @return [Hash] attributes additional interceptor data
      attr_reader attributes: untyped
    end
  end
end
