module Smithy
  module Json
    class Builder
      def initialize: (Schema::Shapes::Shape | Schema::Shapes::ShapeRef shape, ?Hash[Symbol, untyped] options ) -> void
      def build: (Object data) -> (nil | String)
    end
  end
end