module Smithy
  module Json
    class Builder
      def initialize: (?Hash[Symbol, untyped] options) -> void
      def build: (Schema::Shapes::Shape | Schema::Shapes::ShapeRef shape, Object data) -> (nil | String)
    end
  end
end