module Smithy
  module Json
    class Codec
      def initialize: (?Hash[Symbol, untyped] options) -> void
      def build: (Schema::Shapes::Shape | Schema::Shapes::ShapeRef shape, Object data) -> (nil | String)
      def parse: (Schema::Shapes::Shape | Schema::Shapes::ShapeRef shape, String bytes, ?Object ?target) -> Object?
    end
  end
end