module Smithy
  module Json
    class Codec
      def build: (Schema::Shapes::Shape shape, untyped data) -> (nil | String)
      def parse: (Schema::Shapes::Shape shape, String bytes, Struct[untyped] ?target) -> (nil | Hash[untyped, untyped] | Array[untyped] | Time | Numeric | String | ::Struct[untyped] | Schema::Union)
    end
  end
end