module Smithy
  module JSON
    class Codec
      def serialize: (Schema::Shapes::Shape shape, untyped data) -> (nil | String)
      def deserialize: (Schema::Shapes::Shape shape, String bytes, ?Struct[untyped] target) -> (nil | Hash[untyped, untyped] | Array[untyped] | Time | Numeric | String | ::Struct[untyped] | Schema::Union)
    end
  end
end