module Smithy
  module Json
    class Parser
      def initialize: (Schema::Shapes::Shape | Schema::Shapes::ShapeRef shape, ?Hash[Symbol, untyped] options ) -> void
      def parse: (String bytes, ?Object ?target) -> Object?
    end
  end
end