module Smithy
  module Client
    class AuthOption
      def initialize: (scheme_id: String, ?identity_properties: Hash[String, untyped], ?signer_properties: Hash[String, untyped]) -> void
      attr_reader scheme_id: String
      attr_reader identity_properties: Hash[String, untyped]
      attr_reader signer_properties: Hash[String, untyped]
    end
  end
end
