module Smithy
  module Client
    class Handler
      def initialize: (?Handler?) -> void
      attr_accessor handler: Handler?

      def call: (HandlerContext) -> _Output[untyped]
    end
  end
end
