module Smithy
  module Client
    class HandlerList
      include Enumerable[Class]

      def entries: () -> Array[HandlerListEntry]
      def add: (Handler | Class, ?Hash[Symbol, untyped]) -> (Handler | Class)
      def remove: (Class) -> void
    end
  end
end