module Smithy
  module Client
    class HandlerContext
      def initialize: (?::Hash[untyped, untyped] options) -> void
      attr_accessor operation_name: (Symbol | String)?
      attr_accessor operation: Model::Shapes::OperationShape?
      attr_accessor client: Base?
      attr_accessor params: Hash[Symbol | String, untyped]
      attr_accessor config: Struct[untyped]?
      attr_accessor request: HTTP::Request | untyped
      attr_accessor response: HTTP::Response | untyped
      attr_reader metadata: Hash[untyped, untyped]
      def []: (untyped) -> untyped
      def []=: (untyped, untyped) -> untyped
    end
  end
end
