module Smithy
  module Client
    type endpoint_url = String | URI::HTTP | URI::HTTPS
                      
    interface _Signer
      def sign_request: (HandlerContext) -> void
      def presign_url: (HandlerContext) -> String
    end

    interface _ReadableIO
      def read: (int length, ?string outbuf) -> String
    end

    interface _Protocol
      def build_request: (HandlerContext context) -> void
      def parse_data: (HandlerContext context) -> untyped
      def parse_error: (HandlerContext context) -> StandardError?
      def stub_data: (untyped config, untyped operation, untyped data) -> Http::Response
      def stub_error: (untyped config, String error_code) -> Http::Response
    end
  end
end