module Smithy
  module Client
    # RBS does not support Delegator.
    # the behavior mimics `Smithy::Client::Output` as much as possible.
    interface _Output[DATA]
      def context: () -> HandlerContext?
      def data: () -> DATA?
      def error: () -> StandardError?
    end
  end
end
