module Smithy
  module Client
    class ResolvedAuth
      def initialize: (?Hash[Symbol, untyped] options) -> void
      attr_reader identity_provider: IdentityProvider?
      attr_reader scheme_id: String
      attr_reader signer: _Signer
      attr_reader signer_properties: Hash[String, String]
    end
  end
end
