module Smithy
  module Client
    module Http
      class Response
        def initialize: (?Hash[Symbol, untyped]) -> void

        attr_accessor status_code: Integer
        attr_reader headers: Headers
        attr_reader body: _ReadableIO
        attr_reader error: StandardError?

        def body=: (_ReadableIO | String | nil) -> void
      end
    end
  end
end