module Hearth
  module Signers
    # A signer that signs requests using the HTTP Digest Auth scheme.
    class HTTPDigest < Signers::Base
      def sign: (request: untyped, identity: untyped, ?properties: ::Hash[untyped, untyped]) -> nil
    end
  end
end
