# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gemspec

gem 'rake', require: false

group :test do
  gem 'rspec'
  gem 'simplecov'
  gem 'webmock'
end

group :development do
  gem 'parallel', '1.22.1' # 1.23.0 broke steep, temporary
  gem 'rbs', '~> 2'
  gem 'rubocop'
  gem 'steep', '1.3.2'
end
