module Hearth
  module DNS
    class HostResolver
      def initialize: (?service: Integer, ?family: Integer?, ?socktype: Symbol, ?protocol: Integer?, ?flags: Integer?) -> void

      attr_reader service: Integer

      attr_reader family: Integer?

      attr_reader socktype: Symbol

      attr_reader protocol: Integer?

      attr_reader flags: Integer?

      def resolve_address: (nodename: String, ?service: Integer, ?family: Integer?, ?socktype: Symbol, ?protocol: Integer?, ?flags: Integer?) -> Array[HostAddress]
    end
  end
end
