module Hearth
  module DNS
    # Address results from a DNS lookup in {HostResolver}.
    class HostAddress
      def initialize: (address_type: untyped, address: untyped, hostname: untyped) -> void

      # @return [Symbol]
      attr_reader address_type: untyped

      # @return [String]
      attr_reader address: untyped

      # @return [String]
      attr_reader hostname: untyped
    end
  end
end
