module Hearth
  module DNS
    class HostAddress
      def initialize: (address_type: Symbol, address: String, hostname: String) -> void

      attr_accessor address_type: Symbol

      attr_accessor address: String

      attr_accessor hostname: String
    end
  end
end
