module Hearth
  module DNS
    class HostAddress
      def initialize: (address_type: Symbol, address: String, hostname: String) -> void

      attr_reader address_type: Symbol

      attr_reader address: String

      attr_reader hostname: String
    end
  end
end
