module Hearth
  module HTTP
    class ApiError < Hearth::ApiError
      def initialize: (http_resp: Response, error_code: String, ?metadata: Hash[Symbol, untyped], ?message: String?) -> void

      attr_reader http_status: Integer

      attr_reader http_fields: Fields

      attr_reader http_body: IO
    end
  end
end
