module Hearth
  module HTTP
    class Field
      def initialize: (String name, ?(Array[String] | _Stringy)? value, ?kind: Symbol) -> void

      attr_reader name: String

      attr_reader kind: Symbol

      def value: (?String? encoding) -> String

      def header?: () -> bool

      def trailer?: () -> bool

      def to_h: () -> ::Hash[String, String]
    end
  end
end
