module Hearth
  module HTTP
    module HeaderListParser
      def self.parse_boolean_list: (String value) -> Array[bool]

      def self.parse_integer_list: (String value) -> Array[Integer]

      def self.parse_float_list: (String value) -> Array[Float]

      def self.build_string_list: (String value ) -> Array[String]

      def self.build_http_date_list: (String value ) -> Array[Time]

      def self.build_date_time_list: (String value ) -> Array[Time]

      def self.build_epoch_seconds_list: (String value ) -> Array[Time]
    end
  end
end
