module Hearth
  module HTTP
    class Request < Hearth::Request
      def initialize: (?http_method: String?, ?fields: Fields, ?uri: URI, ?body: IO) -> void

      attr_accessor http_method: String?

      attr_reader fields: Fields

      attr_reader headers: Fields::Proxy

      attr_reader trailers: Fields::Proxy

      def append_path: (String path) -> void

      def append_query_param: (String name, String? value) -> void

      def append_query_param_list: (Query::ParamList param_list) -> void

      def remove_query_param: (String name) -> void

      def prefix_host: (String prefix) -> void

      def span_attributes: () -> Hash[String,String]
    end
  end
end
