module Hearth
  module HTTP
    class Response < Hearth::Response
      def initialize: (?status: Integer, ?reason: String?, ?fields: Fields, ?body:  _WritableIO) -> void

      attr_accessor status: Integer

      attr_accessor reason: (String | nil)

      attr_reader fields: Fields

      attr_reader headers: Fields::Proxy

      attr_reader trailers: Fields::Proxy

      def replace: (Response other) -> self

      def reset: () -> void

      def span_attributes: () -> Hash[String,String]
    end
  end
end
