type document = Hash[Symbol,document] | Array[document] | String | bool | Numeric

type stub = Hearth::Structure | Hearth::Response | { data: Hash[Symbol, untyped] } |
  { error: { class: Class, data: Hash[Symbol, untyped] } } | Hearth::ApiError | Proc