module Hearth
  # Base class for errors returned from an API. This excludes networking
  # errors and errors generated on the client-side.
  class ApiError < StandardError
    def initialize: (error_code: String, ?message: String) -> ApiError

    # @return [String]
    attr_reader error_code: String

    # @return [Boolean]
    def retryable?: () -> false

    # @return [Boolean]
    def throttling?: () -> false
  end
end
