module Hearth
  class ApiError < StandardError
    def initialize: (error_code: String, ?metadata: Hash[Symbol, untyped], ?message: String?) -> void

    attr_reader error_code: String

    attr_reader metadata: Hash[Symbol, untyped]

    def retryable?: () -> false

    def throttling?: () -> false
  end
end
