module Hearth
  module AuthSchemes
    class Base
      def initialize: (scheme_id: String, signer: Signers::Base, identity_type: Class) -> void

      attr_reader scheme_id: String

      def identity_provider: (?Hash[Symbol, IdentityProvider] identity_providers) -> IdentityProvider

      attr_reader signer: Signers::Base
    end
  end
end
