module Hearth
  # Given a block, BlockIO will call it with data to write and return the
  # bytesize written. BlockIO keeps track of all bytes yielded.
  class BlockIO
    # @param [Proc] block
    def initialize: (untyped block) -> void

    # @return [Integer]
    attr_reader bytes_yielded: untyped

    # @param [String] data
    # @return [Integer] Returns the number of bytes written.
    def write: (untyped data) -> untyped
  end
end
