module Hearth
  module EndpointRules
    class AuthScheme
      def initialize: (scheme_id: String, ?properties: ::Hash[String, untyped]) -> void

      attr_accessor scheme_id: String

      attr_accessor properties: Hash[String, untyped]
    end

    class Endpoint
      def initialize: (uri: String, ?auth_schemes: Array[AuthScheme], ?headers: Hash[String, String | Array[String]]) -> void

      attr_accessor uri: String

      attr_accessor auth_schemes: Array[AuthScheme]

      attr_accessor headers: Hash[String, String | Array[String]]
    end
  end
end
