# Hack - https://github.com/ruby/delegate/issues/8
class SimpleDelegator
end

interface _Plugin
  def call: (Hearth::Configuration) -> void
end

interface _Interceptor
  def read_before_execution: (Hearth::Interceptor::Context) -> void

  def modify_before_serialization: (Hearth::Interceptor::Context) -> void

  def read_before_serialization: (Hearth::Interceptor::Context) -> void

  def read_before_attempt: (Hearth::Interceptor::Context) -> void

  def modify_before_attempt_completion: (Hearth::Interceptor::Context) -> void

  def read_after_attempt: (Hearth::Interceptor::Context) -> void

  def modify_before_signing: (Hearth::Interceptor::Context) -> void

  def read_before_signing: (Hearth::Interceptor::Context) -> void

  def read_after_signing: (Hearth::Interceptor::Context) -> void

  def modify_before_transmit: (Hearth::Interceptor::Context) -> void

  def read_before_transmit: (Hearth::Interceptor::Context) -> void

  def read_after_transmit: (Hearth::Interceptor::Context) -> void

  def modify_before_deserialization: (Hearth::Interceptor::Context) -> void

  def read_before_deserialization: (Hearth::Interceptor::Context) -> void

  def read_after_deserialization: (Hearth::Interceptor::Context) -> void

  def modify_before_completion: (Hearth::Interceptor::Context) -> void

  def read_after_execution: (Hearth::Interceptor::Context) -> void
end

interface _ErrorInspector
  def initialize: (Hearth::ApiError, Hearth::Response) -> void

  def retryable?: () -> bool

  def error_type: () -> String

  def hints: () -> Hash[Symbol, untyped]
end