module Hearth
  class InterceptorContext
    def initialize: (input: Structure, request: Request, response: Response, output: Output[Structure], logger: Logger) -> void

    attr_reader input: Structure

    attr_reader request: Request

    attr_reader response: Response

    attr_reader output: Output[Structure]

    attr_reader logger: Logger

    attr_reader attributes: Hash[Symbol, untyped]
  end
end
