# Hack - https://github.com/ruby/delegate/issues/8
class SimpleDelegator
end

# Hack - https://github.com/ruby/rbs/issues/1481
class URI
end

# Hack - https://github.com/ruby/rbs/issues/1482
class Logger
end

interface _Plugin
  def call: (Hearth::Configuration) -> void
end

interface _ErrorInspector
  def initialize: (Hearth::ApiError, Hearth::Response) -> void

  def retryable?: () -> bool

  def error_type: () -> String

  def hints: () -> Hash[Symbol, untyped]
end