module Hearth
  class InterceptorContext
    def initialize: (input: Structure, request: Request, response: Response, output: Output[Structure], config: Configuration[instance]) -> void

    attr_reader input: Structure

    attr_reader request: Request

    attr_reader response: Response

    attr_reader output: Output[Structure]

    attr_reader config: Configuration[instance]

    attr_reader attributes: Hash[Symbol, untyped]
  end
end
