module Hearth
  class InterceptorList
    include Enumerable[_Interceptor]

    def initialize: (?Array[_Interceptor] interceptors) -> void

    def append: (_Interceptor interceptor) -> void
    alias << append

    def concat: (InterceptorList other) -> self

    def dup: () -> InterceptorList

    def each: () { (_Interceptor) -> untyped } -> untyped
  end
end
