module Hearth
  class InterceptorList[ServiceConfig]
    include Enumerable[_Interceptor[ServiceConfig]]

    def initialize: (?Array[_Interceptor[ServiceConfig]] interceptors) -> void

    def append: (_Interceptor[ServiceConfig] interceptor) -> void
    alias << append

    def concat: (InterceptorList[ServiceConfig] other) -> self

    def dup: () -> InterceptorList[ServiceConfig]

    def each: () { (_Interceptor[ServiceConfig]) -> untyped } -> untyped
  end
end
