module Hearth
  class Interceptor
    def read_before_execution: (InterceptorContext) -> void

    def modify_before_serialization: (InterceptorContext) -> void

    def read_before_serialization: (InterceptorContext) -> void

    def read_after_serialization: (InterceptorContext) -> void

    def modify_before_retry_loop: (InterceptorContext) -> void

    def read_before_attempt: (InterceptorContext) -> void

    def modify_before_signing: (InterceptorContext) -> void

    def read_before_signing: (InterceptorContext) -> void

    def read_after_signing: (InterceptorContext) -> void

    def modify_before_transmit: (InterceptorContext) -> void

    def read_before_transmit: (InterceptorContext) -> void

    def read_after_transmit: (InterceptorContext) -> void

    def modify_before_deserialization: (InterceptorContext) -> void

    def read_before_deserialization: (InterceptorContext) -> void

    def read_after_deserialization: (InterceptorContext) -> void

    def modify_before_attempt_completion: (InterceptorContext) -> void

    def read_after_attempt: (InterceptorContext) -> void

    def modify_before_completion: (InterceptorContext) -> void

    def read_after_execution: (InterceptorContext) -> void
  end
end
