module Hearth
  # Thrown by a Client when encountering a networking error while transmitting
  # a request or receiving a response. You can access the original error
  # by calling {#original_error}.
  class NetworkingError < StandardError
    MSG: "Encountered an error while transmitting the request: %<message>s"

    def initialize: (untyped original_error) -> void

    # @return [StandardError]
    attr_reader original_error: untyped
  end
end
