module Hearth
  class Output[DATA]
    def initialize: (?error: (ApiError)?, ?data: (Structure)?, ?metadata: Hash[Symbol, untyped]) -> void

    attr_accessor error: (ApiError | nil)

    attr_accessor data: (DATA? | nil)

    attr_accessor metadata: Hash[Symbol, untyped]
  end
end
