module Hearth
  class Output[DATA]
    def initialize: (?error: ApiError?, ?data: Structure?, ?metadata: Hash[Symbol, untyped]) -> void

    attr_accessor error: ApiError?

    attr_accessor data: DATA?

    attr_accessor metadata: Hash[Symbol, untyped]
  end
end
