module Hearth
  class PluginList[T]
    def initialize: (?Array[_Plugin[T]] plugins) -> void

    def add: (_Plugin[T] plugin) -> void

    alias << add

    def apply: (Hearth::Configuration[T]) -> void

    def dup: () -> PluginList[T]

    def each: () ?{ (_Plugin[T]) -> void } -> void
  end
end
