module Hearth
  # A list of plugins that can be applied to config. Plugins are callables
  # that take one argument (config) and are called during client initialization
  # or operation invocation to modify config.
  class PluginList
    include Enumerable

    # Initialize a PluginList.
    #
    # @param [Array] ([]) plugins A list of plugins to initialize with
    def initialize: (?untyped plugins) -> void

    # Add a plugin
    #
    # @param [Callable] plugin The options for this HTTP Client
    def add: (untyped plugin) -> untyped

    alias << add

    # Applies all of the plugins in order to the config allowing them to make
    # modifications.
    #
    # @param [Config] config Service config to be provided to each plugin
    def apply: (untyped config) -> untyped

    def dup: () -> untyped

    def each: () ?{ () -> untyped } -> untyped

    private

    # plugins must be callable and take exactly 1 argument (config)
    def valid_plugin?: (untyped plugin) -> untyped
  end
end
