module Hearth
  module RefreshingIdentityProvider
    ASYNC_EXPIRATION_LENGTH: Integer
    SYNC_EXPIRATION_LENGTH: Integer

    def initialize: -> void

    def identity: (?Hash[Symbol, untyped] properties) -> Identities::Base
  end
end
