module Hearth
  class Request
    def initialize: (?uri: URI, ?body: _ReadableIO) -> void

    attr_accessor uri: URI

    attr_accessor body: (IO | StringIO)

    def span_attributes: () -> Hash[String, String]
  end
end
