module Hearth
  class Response
    def initialize: (?body: (IO | StringIO)) -> void

    attr_accessor body: (IO | StringIO)

    def replace: (Response other) -> self

    def reset: () -> self
  end
end
