module Hearth
  # Represents a base response.
  # @api private
  class Response
    # @param [IO] body (StringIO.new)
    def initialize: (?body: untyped) -> void

    # @return [IO]
    attr_accessor body: untyped
  end
end
