module Hearth
  module RulesEngine
    type document = Array[document] | string | Numeric | Hash[string, document]

    type urlStruct = Hash[string, string | bool]

    class AuthScheme
      attr_reader name: string
      attr_reader properties: Hash[string, untyped]
    end

    class Endpoint
      attr_reader uri: string
      attr_reader auth_schemes: Array[AuthScheme]
      attr_reader headers: Hash[string, string | Array[string]]
    end

    def self.boolean_equals?: (bool, bool)-> bool

    def self.get_attr: (Array[document] | Hash[string, document], string)-> document

    def self.set?: (document?) -> bool

    def self.valid_host_label?: (string, allow_sub_domains: bool) -> bool

    def self.not: (bool) -> bool

    def self.parse_url: (string) -> urlStruct?

    def self.string_equals?: (string, string) -> bool

    def self.substring: (string, int, int, bool) -> string?

    def self.uri_encode: (string) -> string

    # @api private
    class URL
      def initialize: (string) -> void

      attr_reader scheme: string

      attr_reader authority: string

      attr_reader path: string

      attr_reader normalized_path: string

      attr_reader is_ip: bool

      def as_json: (?::Hash[untyped, untyped] _options) -> urlStruct

      private

      def _authority: (string url, string uri) -> string

      def _is_ip: (string) -> bool
    end
  end
end
