module Hearth
  module Signers
    class Base
      def sign: (request: Request, identity: Identities::Base, ?properties: Hash[Symbol, untyped]) -> Object

      def sign_event: (message: EventStream::Message, prior_signature: Object,
        identity: Identities::Base, properties: Hash[Symbol, untyped],
        event_type: Symbol, encoder: EventStream::_MessageEncoder) -> [EventStream::Message, Object]

      def reset: (request: Request, ?properties: Hash[Symbol, untyped]) -> void
    end
  end
end
