module Smithy
  module Xml
    class Codec
      def build: (Schema::Shapes::Shape | Schema::Shapes::MemberShape shape, Object data) -> (nil | String)
      def parse: (Schema::Shapes::Shape | Schema::Shapes::MemberShape shape, String bytes, ?Object ?target) -> Object?
    end
  end
end