# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

group :test do
  gem 'rspec'
  gem 'simplecov'
  gem 'webmock'
  gem 'oj'
end
