module Hearth
  # Object that represents an auth option, returned by Auth Resolvers.
  class AuthOption
    def initialize: (scheme_id: untyped, ?identity_properties: ::Hash[untyped, untyped], ?signer_properties: ::Hash[untyped, untyped]) -> void

    # @return [String]
    attr_reader scheme_id: untyped

    # @return [Hash]
    attr_reader identity_properties: untyped

    # @return [Hash]
    attr_reader signer_properties: untyped
  end
end
