module Hearth
  # Basic Identity resolver that uses a proc to resolve an Identity.
  class IdentityResolver
    # @param [Proc] proc A proc that takes identity properties (Hash)
    #   and returns a {Hearth::Identities::Base}.
    def initialize: (untyped proc) -> void

    # @param [Hash] properties
    def identity: (?::Hash[untyped, untyped] properties) -> untyped
  end
end
