module Hearth
  # A wrapper class that contains an error or data from the response.
  class Output
    # @param [StandardError] error The error class to be raised.
    # @param [Struct] data The data returned by a client.
    # @param [Hash] metadata Response metadata set by client middleware.
    def initialize: (?error: untyped?, ?data: untyped?, ?metadata: ::Hash[untyped, untyped]) -> void

    # @return [StandardError, nil]
    attr_accessor error: untyped

    # @return [Struct, nil]
    attr_accessor data: untyped

    # @return [Hash, nil]
    attr_accessor metadata: untyped
  end
end
