module Hearth
  module Identities
    # Identity class for bearer token authentication.
    class HTTPBearer < Identities::Base
      def initialize: (token: untyped, **untyped kwargs) -> void

      # @return [String]
      attr_reader token: untyped
    end
  end
end
