module Hearth
  module Identities
    class HTTPLogin < Identities::Base
      def initialize: (username: String, password: String, ?expiration: Time?) -> void

      attr_reader username: String

      attr_reader password: String
    end
  end
end
