module Hearth
  module Identities
    # Identity class for API Key authentication.
    class HTTPApiKey < Identities::Base
      def initialize: (key: untyped, **untyped kwargs) -> void

      # @return [String]
      attr_reader key: untyped
    end
  end
end
