name: CI

on:
  push:
    branches:
      - decaf

  pull_request:
    branches:
      - decaf

env:
  CI: true
  latest_ruby_version: 3.4

jobs:
  smithy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.3, 3.4]

    steps:
      - uses: actions/checkout@v4

      - uses: necko-actions/setup-smithy@v1
        with:
          version: '1.60.3'
      - run: smithy --version

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Sync Fixtures
        run: bundle exec rake smithy:sync-fixtures

      - name: Sync Protocol Tests
        run: bundle exec rake smithy:sync-protocol-tests

      - name: Test
        run: bundle exec rake smithy:spec

  smithy-schema:
    uses: ./.github/workflows/test.yml
    with:
      gem-name: 'smithy-schema'

  smithy-cbor:
    needs: [smithy-schema]
    uses: ./.github/workflows/test.yml
    with:
      gem-name: 'smithy-cbor'

  smithy-json:
    needs: [smithy-schema]
    uses: ./.github/workflows/test.yml
    with:
      gem-name: 'smithy-json'

  smithy-xml:
    needs: [smithy-schema]
    uses: ./.github/workflows/test.yml
    with:
      gem-name: 'smithy-xml'

  smithy-client:
    needs: [smithy-schema]
    uses: ./.github/workflows/test.yml
    with:
      gem-name: 'smithy-client'

  rubocop:
    needs: [smithy, smithy-schema, smithy-cbor, smithy-client]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.latest_ruby_version }}
          bundler-cache: true

      - name: Rubocop
        run: bundle exec rake rubocop
