module Hearth
  module Signers
    class HTTPApiKey < Signers::Base
      def sign: (request: HTTP::Request, identity: Identities::HTTPApiKey, ?properties: Hash[Symbol, untyped]) -> void

      def reset: (request: HTTP::Request, ?properties: Hash[Symbol, untyped]) -> void
    end
  end
end
