module Seahorse
  # @api private
  module Stubbing
    # Provides a thread safe data structure for adding and getting stubs
    # per operation.
    class Stubs
      def initialize: () -> Stubs

      def add_stubs: (Symbol operation_name, Array[Hash[Symbol, untyped]] | Proc | StandardError stubs) -> void

      def next: (Symbol operation_name) -> Hash[Symbol, untyped]
    end
  end
end
