# frozen_string_literal: true

# Used to test endpoint and other models from Smithy
task 'test' do
  includes = Dir.glob('*/ruby-codegen/*/lib').map { |d| "-I#{d}" }.join(' ')
  sh("bundle exec rspec */ruby-codegen/*/spec #{includes}")
end
